#!/usr/bin/env npx tsx
// Turn enrich JSONL into a D1-safe SQL file (quoted, no interpolation of raw objects).
//   npx tsx scripts/enrich-to-sql.mts --in data/enrich.jsonl --out data/enrich.sql
import { createReadStream, createWriteStream, existsSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { resolve } from 'node:path';
import type { EnrichRow } from './enrich-content.mts';

const args = process.argv.slice(2);
const flag = (name: string): string | undefined => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};

const q = (v: string | number | null | undefined): string => {
  if (v == null || v === '') return 'NULL';
  if (typeof v === 'number' && Number.isFinite(v)) return String(Math.round(v));
  return `'${String(v).replace(/'/g, "''")}'`;
};

const ja = (v: string[]): string => q(JSON.stringify(v));

const inPath = resolve(flag('in') ?? 'data/enrich.jsonl');
const outPath = resolve(flag('out') ?? 'data/enrich.sql');
if (!existsSync(inPath)) {
  console.error(`missing ${inPath}`);
  process.exit(1);
}

const out = createWriteStream(outPath);
out.write('-- generated by scripts/enrich-to-sql.mts — do not commit (publisher domains).\n');
// No BEGIN/COMMIT: D1 rejects SQL transaction statements in an executed file.
let n = 0;
const rl = createInterface({ input: createReadStream(inPath), crlfDelay: Infinity });
for await (const line of rl) {
  if (!line.trim()) continue;
  let row: EnrichRow;
  try { row = JSON.parse(line) as EnrichRow; } catch { continue; }
  if (!row.site_id) continue;
  out.write(
    `INSERT INTO site_content (site_id, summary, writes_about, recent_titles, enriched_at, source, audience, tone, post_shape, typical_length_words, do_fit, dont_fit, summary_private, enrich_status)
VALUES (${q(row.site_id)}, ${q(row.summary)}, ${ja(row.writes_about || [])}, ${ja(row.recent_titles || [])}, ${q(row.enriched_at)}, ${q(row.source)}, ${q(row.audience)}, ${q(row.tone)}, ${q(row.post_shape)}, ${q(row.typical_length_words)}, ${q(row.do_fit)}, ${q(row.dont_fit)}, ${q(row.summary_private)}, ${q(row.enrich_status)})
ON CONFLICT(site_id) DO UPDATE SET
  summary=excluded.summary, writes_about=excluded.writes_about, recent_titles=excluded.recent_titles,
  enriched_at=excluded.enriched_at, source=excluded.source, audience=excluded.audience, tone=excluded.tone,
  post_shape=excluded.post_shape, typical_length_words=excluded.typical_length_words, do_fit=excluded.do_fit,
  dont_fit=excluded.dont_fit, summary_private=excluded.summary_private, enrich_status=excluded.enrich_status;\n`,
  );
  n++;
}
out.end();
console.log(`wrote ${n} upserts to ${outPath}`);
